version: '3.0'
services:
  main:
    mem_limit: 0.5GB
    build:
      context: .
    ports:
      - 4006:4006
  postgres:
    container_name: postgres_container
    image: postgres
    mem_limit: 0.5GB
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_kovalskaya_ns
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
